#!/bin/bash
# =============================================================================
# init_project.sh — PYNQ-Z2 ECG Demo Project Initialiser
# Run this once from wherever you want the project to live.
# Usage: bash init_project.sh [project_name]
# =============================================================================

set -e

PROJECT_NAME=${1:-pynq-ecg-demo}
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo ""
echo "  🫀 PYNQ-Z2 ECG Demo — Project Initialiser"
echo "  ==========================================="
echo "  Creating project: $PROJECT_NAME"
echo ""

# -----------------------------------------------------------------------------
# 1. Create root folder
# -----------------------------------------------------------------------------
if [ -d "$PROJECT_NAME" ]; then
  echo "  ⚠️  Folder '$PROJECT_NAME' already exists."
  read -p "     Overwrite? This will not delete existing files. (y/N): " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { echo "  Aborted."; exit 0; }
fi

mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

# -----------------------------------------------------------------------------
# 2. Create directory structure
# -----------------------------------------------------------------------------
echo "  📁 Creating directories..."

dirs=(
  "agents"
  "handoffs"
  "algo/plots"
  "pl"
  "sim/results"
  "sim/test_ecg_dds"
  "sim/test_spi_dac"
  "sim/test_spi_adc"
  "sim/test_fir_filter"
  "sim/test_rpeak_detector"
  "sim/test_axi_ecg_ctrl"
  "ps"
  "pc"
  "docs/images"
  "scripts"
)

for dir in "${dirs[@]}"; do
  mkdir -p "$dir"
  echo "     ✓ $dir/"
done

# -----------------------------------------------------------------------------
# 3. Create placeholder files to mark ownership
# -----------------------------------------------------------------------------
echo ""
echo "  📄 Creating placeholder files..."

placeholders=(
  "handoffs/register_map.md|# Register Map\n_Pending — generated by pynq_ecg_gen at Milestone 1_"
  "handoffs/adc_interface.md|# ADC Interface\n_Pending — generated by pynq_ecg_gen at Milestone 1_"
  "handoffs/algorithm_spec.md|# Algorithm Specification\n_Pending — generated by pynq_ecg_algo at Milestone 2_"
  "handoffs/ws_schema.json|{}\n"
  "handoffs/simulation_results.md|# Simulation Results\n_Pending — generated by pynq_simulation at Milestone 4_"
  "docs/architecture.md|# Architecture\n_Pending — generated by pynq_docs at Milestone 1_"
  "docs/wiring_guide.md|# Wiring Guide\n_Pending — generated by pynq_docs at Milestone 1_"
  "docs/algorithm_summary.md|# Algorithm Summary\n_Pending — generated by pynq_docs at Milestone 2_"
  "docs/register_map.md|# Register Map\n_Pending — generated by pynq_docs at Milestone 1_"
  "docs/simulation_report.md|# Simulation Report\n_Pending — generated by pynq_docs at Milestone 4_"
  "docs/api_reference.md|# API Reference\n_Pending — generated by pynq_docs at Milestone 5_"
  "docs/setup_guide.md|# Setup Guide\n_Pending — generated by pynq_docs at Milestone 6_"
)

for entry in "${placeholders[@]}"; do
  file="${entry%%|*}"
  content="${entry##*|}"
  printf "$content\n" > "$file"
  echo "     ✓ $file"
done

# -----------------------------------------------------------------------------
# 4. Create .claudeignore templates in scripts/
# -----------------------------------------------------------------------------
echo ""
echo "  🔧 Creating .claudeignore templates..."

cat > scripts/ignore_for_ecg_gen.txt << 'EOF'
sim/
ps/
pc/
docs/
algo/
EOF

cat > scripts/ignore_for_ecg_algo.txt << 'EOF'
pl/
sim/
ps/
pc/
docs/
EOF

cat > scripts/ignore_for_ecg_process.txt << 'EOF'
sim/
ps/
pc/
docs/
EOF

cat > scripts/ignore_for_simulation.txt << 'EOF'
ps/
pc/
docs/
EOF

cat > scripts/ignore_for_ps_server.txt << 'EOF'
pl/
sim/
pc/
algo/
EOF

cat > scripts/ignore_for_gui.txt << 'EOF'
pl/
sim/
ps/
algo/
EOF

cat > scripts/ignore_for_docs.txt << 'EOF'
EOF

echo "     ✓ scripts/ignore_for_ecg_gen.txt"
echo "     ✓ scripts/ignore_for_ecg_algo.txt"
echo "     ✓ scripts/ignore_for_ecg_process.txt"
echo "     ✓ scripts/ignore_for_simulation.txt"
echo "     ✓ scripts/ignore_for_ps_server.txt"
echo "     ✓ scripts/ignore_for_gui.txt"
echo "     ✓ scripts/ignore_for_docs.txt"

# -----------------------------------------------------------------------------
# 5. Create swap_agent.sh helper
# -----------------------------------------------------------------------------
cat > scripts/swap_agent.sh << 'EOF'
#!/bin/bash
# Usage: ./scripts/swap_agent.sh <agent_name>
# Example: ./scripts/swap_agent.sh pynq_ecg_gen

AGENT=$1
IGNORE_FILE="scripts/ignore_for_${AGENT#pynq_}.txt"

if [ -z "$AGENT" ]; then
  echo "Usage: $0 <agent_name>"
  echo "Agents: pynq_ecg_gen, pynq_ecg_algo, pynq_ecg_process,"
  echo "        pynq_simulation, pynq_ps_server, pynq_gui, pynq_docs"
  exit 1
fi

if [ ! -f "$IGNORE_FILE" ]; then
  echo "No ignore template found for '$AGENT' (looked for $IGNORE_FILE)"
  exit 1
fi

cp "$IGNORE_FILE" .claudeignore
echo "✓ .claudeignore set for $AGENT"
echo "  Now run: claude   (or aider for Gemini agents)"
EOF
chmod +x scripts/swap_agent.sh
echo "     ✓ scripts/swap_agent.sh"

# -----------------------------------------------------------------------------
# 6. Create .gitignore
# -----------------------------------------------------------------------------
cat > .gitignore << 'EOF'
# Vivado
*.jou
*.log
*.str
*.xpr
*.bit
*.hwh
vivado_project/

# Python
__pycache__/
*.pyc
.env
venv/

# Simulation
sim/results/*.vcd
sim/test_*/sim_build/
sim/test_*/__pycache__/

# Plots (regenerated by algo agent)
algo/plots/

# Streamlit
.streamlit/

# OS
.DS_Store
EOF
echo "     ✓ .gitignore"

# -----------------------------------------------------------------------------
# 7. Create CLAUDE.md
# -----------------------------------------------------------------------------
cat > CLAUDE.md << 'EOF'
# PYNQ-Z2 ECG Demo

## For Claude Code
You are the orchestrator for this project.
Read `agents/pynq_orchestrator.md` completely before doing anything else.
Do not write any code or create any files until you have read it.

## Current Milestone
<!-- UPDATE THIS MANUALLY AFTER EACH MILESTONE IS APPROVED -->
CURRENT: 0 — Not started

## Active Agent Session
<!-- UPDATE THIS WHEN SWITCHING AGENTS -->
AGENT: pynq_orchestrator

## Switching Agents
Run this before starting each agent session:
  bash scripts/swap_agent.sh pynq_ecg_gen
  bash scripts/swap_agent.sh pynq_ecg_algo
  bash scripts/swap_agent.sh pynq_ecg_process
  bash scripts/swap_agent.sh pynq_simulation
  bash scripts/swap_agent.sh pynq_ps_server
  bash scripts/swap_agent.sh pynq_gui
  bash scripts/swap_agent.sh pynq_docs

## Context Saving
- Run /compact when context feels heavy
- Update CURRENT milestone above before closing a session
EOF
echo "     ✓ CLAUDE.md"

# -----------------------------------------------------------------------------
# 8. Check if agent files need to be copied in
# -----------------------------------------------------------------------------
echo ""
echo "  📋 Checking for agent prompt files..."

agents=(
  "pynq_orchestrator.md"
  "pynq_ecg_gen.md"
  "pynq_ecg_algo.md"
  "pynq_ecg_process.md"
  "pynq_simulation.md"
  "pynq_ps_server.md"
  "pynq_gui.md"
  "pynq_docs.md"
)

missing=0
for agent in "${agents[@]}"; do
  if [ -f "agents/$agent" ]; then
    echo "     ✓ agents/$agent"
  else
    echo "     ✗ agents/$agent  ← MISSING — copy this in manually"
    missing=$((missing + 1))
  fi
done

# -----------------------------------------------------------------------------
# 9. Toolchain check
# -----------------------------------------------------------------------------
echo ""
echo "  🔍 Toolchain check..."

check_tool() {
  if command -v "$1" &> /dev/null; then
    echo "     ✓ $1"
  else
    echo "     ✗ $1  ← not found (see SETUP.md)"
  fi
}

check_tool iverilog
check_tool gtkwave
check_tool python3
check_tool claude
check_tool aider

python3 -c "import cocotb" 2>/dev/null \
  && echo "     ✓ cocotb" \
  || echo "     ✗ cocotb  ← pip install cocotb"

python3 -c "import numpy, scipy" 2>/dev/null \
  && echo "     ✓ numpy + scipy" \
  || echo "     ✗ numpy/scipy  ← pip install numpy scipy"

python3 -c "import streamlit" 2>/dev/null \
  && echo "     ✓ streamlit" \
  || echo "     ✗ streamlit  ← pip install streamlit"

# -----------------------------------------------------------------------------
# 10. Done
# -----------------------------------------------------------------------------
echo ""
echo "  ✅ Project initialised: $(pwd)"
echo ""

if [ "$missing" -gt 0 ]; then
  echo "  ⚠️  $missing agent prompt file(s) missing."
  echo "     Download them and place in agents/ before running Claude Code."
  echo ""
fi

echo "  Next steps:"
echo "   1. Copy agent .md files into agents/  (if not already there)"
echo "   2. Install missing tools listed above  (see SETUP.md)"
echo "   3. bash scripts/swap_agent.sh pynq_orchestrator"
echo "   4. claude"
echo ""
